-- =====================================================================
--  Controle de Estoque — Seed (Lista 2: produtos e embalagens)
--  Rode DEPOIS de schema.sql. Pode rodar de novo: usa ON CONFLICT.
--  tipo e capacidade sao calculados automaticamente a partir da descricao.
-- =====================================================================

-- ---------------------------------------------------------------------
--  Produtos
-- ---------------------------------------------------------------------
insert into public.produtos (nome) values
  ('ACCELIK AS'),
  ('ACCELIK SF'),
  ('ACCETIVE FC POWDER'),
  ('ACEPESS FAST'),
  ('ACS 800'),
  ('ADIGROUT AR'),
  ('ADIGROUT AR COMPLETE'),
  ('ADIGROUT MC'),
  ('ADIGROUT MIX'),
  ('ADIGROUT MIX CONCRETE'),
  ('ADIGROUT TIX'),
  ('ADIGROUT UFR'),
  ('ADIGROUT WHITE'),
  ('AGRECON POWDER'),
  ('ARGAPOL 592 IC Conjunto'),
  ('ARGAPOL 992 Conjunto'),
  ('ARGAPOL BC Conjunto'),
  ('ARGAPOL MRI'),
  ('ARGAPOL RE 642'),
  ('CEPAS INJECT'),
  ('CEPAS INJECT BC'),
  ('CI 900'),
  ('CURE CA'),
  ('DRAMOR POWDER'),
  ('EDIMPER M'),
  ('EDIMPER PLUS'),
  ('EXPANDER 2019'),
  ('EXPANFLUID IC'),
  ('FASTER'),
  ('FLUXYGROUT HMR CONJUNTO'),
  ('FLUXYGROUT SOFT CONJUNTO'),
  ('HYDROFLEX S A'),
  ('HYDROFLEX SEL'),
  ('HYDROFLEX RR'),
  ('HYDROFLEX RS'),
  ('HYDROFLEX S'),
  ('HYDROFLEX V2'),
  ('INCORPOR BS PLUS'),
  ('INCORPOR BS-D'),
  ('KOLA'),
  ('KOLA PLUS TIX'),
  ('KOLA PVA'),
  ('KOLA SBR'),
  ('KOLA SUPER'),
  ('LIKTIVE ACEP UF'),
  ('MINERAL REPAIR 132 Conjunto'),
  ('MINERAL REPAIR 333 Conjunto'),
  ('MINERAL REPAIR 499 Conjunto'),
  ('PLASTICIZER BINDER'),
  ('PLASTICIZER CW'),
  ('PLASTICIZER HC'),
  ('PLASTICIZER PREMIUM'),
  ('PLASTICIZER SAD'),
  ('PLASTICIZER SAD 20'),
  ('POLYPLAST 146'),
  ('POLYPLAST 151'),
  ('POLYPLAST 167'),
  ('POLYPLAST 170 D'),
  ('POLYPLAST 170 PLUS'),
  ('POLYPLAST 4300'),
  ('POLYSEL CONJUNTO'),
  ('PRIME JD CONJUNTO'),
  ('RELEASE WAX'),
  ('RELENT'),
  ('RELENT AD'),
  ('RELENT BASE'),
  ('RELENT BIO-VO'),
  ('RELENT CONCENTRATE'),
  ('RELENT RTU'),
  ('RELENT S'),
  ('RELENT SMO'),
  ('RELENT SUPER'),
  ('RELENT W'),
  ('RETARPEG S'),
  ('RETARTIVE WR 2010'),
  ('RETARTIVE WR 2048'),
  ('RUST CONVERTER'),
  ('STRUCTURAL AD CONJUNTO'),
  ('STRUCTURAL TF CONJUNTO'),
  ('SUPERFLUID AC'),
  ('WHITE MINERAL REPAIR CONJUNTO'),
  ('WP ARCON'),
  ('WP ARPOMON'),
  ('WP CRYSTAL'),
  ('WP FLEXIBLE'),
  ('WP HYDRACEM UF'),
  ('SUFLEX GREY RA'),
  ('SUFLEXIBLE RA'),
  ('SUPROFLEX CONJUNTO'),
  ('WP TILE PRO')
on conflict (nome) do nothing;

-- ---------------------------------------------------------------------
--  Embalagens (descricao -> tipo/capacidade calculados pelo schema)
-- ---------------------------------------------------------------------
insert into public.embalagens (produto_id, descricao)
select p.id, v.descricao
from public.produtos p
join (values
  ('ACCELIK AS','Bombona 25'),
  ('ACCELIK AS','Bombona 60'),
  ('ACCELIK AS','Tambor 250'),
  ('ACCELIK AS','CNT 1250'),
  ('ACCELIK SF','Bombona 25'),
  ('ACCELIK SF','Bombona 60'),
  ('ACCELIK SF','Tambor 250'),
  ('ACCELIK SF','CNT 1250'),
  ('ACCETIVE FC POWDER','Saco 20'),
  ('ACEPESS FAST','Bombona 24'),
  ('ACEPESS FAST','Bombona 60'),
  ('ACEPESS FAST','Tambor 240'),
  ('ACEPESS FAST','CNT 1200'),
  ('ACS 800','Bombona 20'),
  ('ACS 800','Bombona 50'),
  ('ACS 800','Tambor 200'),
  ('ACS 800','CNT 1000'),
  ('ADIGROUT AR','Saco 25'),
  ('ADIGROUT AR COMPLETE','Saco 25'),
  ('ADIGROUT MC','Saco 25'),
  ('ADIGROUT MIX','Saco 10'),
  ('ADIGROUT MIX CONCRETE','Saco 10'),
  ('ADIGROUT TIX','Saco 25'),
  ('ADIGROUT UFR','Saco 25'),
  ('ADIGROUT WHITE','Saco 25'),
  ('AGRECON POWDER','Saco 8'),
  ('ARGAPOL 592 IC Conjunto','Conjunto 35,4'),
  ('ARGAPOL 992 Conjunto','Conjunto 6'),
  ('ARGAPOL BC Conjunto','Conjunto 35'),
  ('ARGAPOL MRI','Saco 20'),
  ('ARGAPOL RE 642','Saco 25'),
  ('CEPAS INJECT','Saco 20'),
  ('CEPAS INJECT BC','Saco 20'),
  ('CI 900','Bombona 20'),
  ('CI 900','Bombona 50'),
  ('CI 900','Tambor 200'),
  ('CI 900','CNT 100'),
  ('CURE CA','Bombona 20'),
  ('CURE CA','Bombona 50'),
  ('CURE CA','Tambor 200'),
  ('CURE CA','CNT 1000'),
  ('DRAMOR POWDER','Saco 20'),
  ('EDIMPER M','Bombona 20'),
  ('EDIMPER M','Bombona 50'),
  ('EDIMPER M','Tambor 200'),
  ('EDIMPER M','CNT 1000'),
  ('EDIMPER PLUS','Bombona 25'),
  ('EDIMPER PLUS','Bombona 60'),
  ('EDIMPER PLUS','Tambor 250'),
  ('EDIMPER PLUS','CNT 1250'),
  ('EXPANDER 2019','Saco 10'),
  ('EXPANFLUID IC','Saco 10'),
  ('FASTER','Bombona 24'),
  ('FASTER','Bombona 60'),
  ('FASTER','Tambor 240'),
  ('FASTER','CNT 1200'),
  ('FLUXYGROUT HMR CONJUNTO','Conjunto 22'),
  ('FLUXYGROUT SOFT CONJUNTO','Conjunto 28'),
  ('HYDROFLEX S A','Bombona 20'),
  ('HYDROFLEX S A','Bombona 50'),
  ('HYDROFLEX S A','Tambor 200'),
  ('HYDROFLEX S A','CNT 1000'),
  ('HYDROFLEX SEL','Bombona 20'),
  ('HYDROFLEX SEL','Bombona 50'),
  ('HYDROFLEX RR','Bombona 20'),
  ('HYDROFLEX RR','Bombona 50'),
  ('HYDROFLEX RR','Tambor 200'),
  ('HYDROFLEX RR','CNT 1000'),
  ('HYDROFLEX RS','Bombona 20'),
  ('HYDROFLEX RS','Bombona 50'),
  ('HYDROFLEX RS','Tambor 200'),
  ('HYDROFLEX RS','CNT 1000'),
  ('HYDROFLEX S','Bombona 20'),
  ('HYDROFLEX S','Bombona 50'),
  ('HYDROFLEX S','Tambor 200'),
  ('HYDROFLEX S','CNT 1000'),
  ('HYDROFLEX V2','Bombona 20'),
  ('HYDROFLEX V2','Bombona 50'),
  ('INCORPOR BS PLUS','Bombona 20'),
  ('INCORPOR BS PLUS','Bombona 50'),
  ('INCORPOR BS PLUS','Tambor 200'),
  ('INCORPOR BS PLUS','CNT 1000'),
  ('INCORPOR BS-D','Bombona 20'),
  ('INCORPOR BS-D','Bombona 50'),
  ('INCORPOR BS-D','Tambor 200'),
  ('INCORPOR BS-D','CNT 1000'),
  ('KOLA','Bombona 20'),
  ('KOLA','Bombona 50'),
  ('KOLA','Tambor 200'),
  ('KOLA','CNT 1000'),
  ('KOLA PLUS TIX','Bombona 20'),
  ('KOLA PLUS TIX','Bombona 50'),
  ('KOLA PLUS TIX','Tambor 200'),
  ('KOLA PLUS TIX','CNT 1000'),
  ('KOLA PVA','Bombona 20'),
  ('KOLA PVA','Bombona 50'),
  ('KOLA PVA','Tambor 200'),
  ('KOLA SBR','Bombona 20'),
  ('KOLA SBR','Bombona 50'),
  ('KOLA SBR','Tambor 200'),
  ('KOLA SBR','CNT 1000'),
  ('KOLA SUPER','Bombona 20'),
  ('KOLA SUPER','Bombona 50'),
  ('KOLA SUPER','Tambor 200'),
  ('KOLA SUPER','CNT 1000'),
  ('LIKTIVE ACEP UF','Bombona 25'),
  ('LIKTIVE ACEP UF','Bombona 60'),
  ('LIKTIVE ACEP UF','Tambor 250'),
  ('MINERAL REPAIR 132 Conjunto','Conjunto 40'),
  ('MINERAL REPAIR 333 Conjunto','Conjunto 40'),
  ('MINERAL REPAIR 499 Conjunto','Conjunto 40'),
  ('PLASTICIZER BINDER','Bombona 20'),
  ('PLASTICIZER BINDER','Bombona 50'),
  ('PLASTICIZER BINDER','Tambor 200'),
  ('PLASTICIZER BINDER','CNT 1000'),
  ('PLASTICIZER CW','Bombona 20'),
  ('PLASTICIZER CW','Bombona 50'),
  ('PLASTICIZER CW','Tambor 200'),
  ('PLASTICIZER CW','CNT 1000'),
  ('PLASTICIZER HC','Bombona 20'),
  ('PLASTICIZER HC','Bombona 50'),
  ('PLASTICIZER HC','Tambor 200'),
  ('PLASTICIZER HC','CNT 1000'),
  ('PLASTICIZER PREMIUM','Bombona 20'),
  ('PLASTICIZER PREMIUM','Bombona 50'),
  ('PLASTICIZER PREMIUM','Tambor 200'),
  ('PLASTICIZER PREMIUM','CNT 1000'),
  ('PLASTICIZER SAD','Bombona 20'),
  ('PLASTICIZER SAD','Bombona 50'),
  ('PLASTICIZER SAD','Tambor 200'),
  ('PLASTICIZER SAD','CNT 1000'),
  ('PLASTICIZER SAD 20','Bombona 20'),
  ('PLASTICIZER SAD 20','Bombona 50'),
  ('PLASTICIZER SAD 20','Tambor 200'),
  ('PLASTICIZER SAD 20','CNT 1000'),
  ('POLYPLAST 146','Bombona 24'),
  ('POLYPLAST 146','Bombona 60'),
  ('POLYPLAST 146','Tambor 240'),
  ('POLYPLAST 146','CNT 1200'),
  ('POLYPLAST 151','Bombona 24'),
  ('POLYPLAST 151','Bombona 60'),
  ('POLYPLAST 151','Tambor 240'),
  ('POLYPLAST 151','CNT 1200'),
  ('POLYPLAST 167','Bombona 24'),
  ('POLYPLAST 167','Bombona 60'),
  ('POLYPLAST 167','Tambor 240'),
  ('POLYPLAST 167','CNT 1200'),
  ('POLYPLAST 170 D','Bombona 24'),
  ('POLYPLAST 170 D','Bombona 60'),
  ('POLYPLAST 170 D','Tambor 240'),
  ('POLYPLAST 170 D','CNT 1200'),
  ('POLYPLAST 170 PLUS','Bombona 24'),
  ('POLYPLAST 170 PLUS','Bombona 60'),
  ('POLYPLAST 170 PLUS','Tambor 240'),
  ('POLYPLAST 170 PLUS','CNT 1200'),
  ('POLYPLAST 4300','Bombona 24'),
  ('POLYPLAST 4300','Bombona 60'),
  ('POLYPLAST 4300','Tambor 240'),
  ('POLYPLAST 4300','CNT 1200'),
  ('POLYSEL CONJUNTO','Conjunto 5'),
  ('PRIME JD CONJUNTO','Conjunto 1'),
  ('RELEASE WAX','Balde 18'),
  ('RELENT','Bombona 20'),
  ('RELENT','Bombona 50'),
  ('RELENT','Tambor 200'),
  ('RELENT','CNT 1000'),
  ('RELENT AD','Bombona 20'),
  ('RELENT AD','Bombona 50'),
  ('RELENT AD','Tambor 200'),
  ('RELENT AD','CNT 1000'),
  ('RELENT BASE','Tambor 200'),
  ('RELENT BIO-VO','Bombona 20'),
  ('RELENT BIO-VO','Bombona 50'),
  ('RELENT BIO-VO','Tambor 200'),
  ('RELENT BIO-VO','CNT 1000'),
  ('RELENT CONCENTRATE','Bombona 20'),
  ('RELENT CONCENTRATE','Bombona 50'),
  ('RELENT CONCENTRATE','Tambor 200'),
  ('RELENT CONCENTRATE','CNT 1000'),
  ('RELENT RTU','Bombona 20'),
  ('RELENT RTU','Bombona 50'),
  ('RELENT RTU','Tambor 200'),
  ('RELENT RTU','CNT 1000'),
  ('RELENT S','Bombona 20'),
  ('RELENT S','Bombona 50'),
  ('RELENT S','Tambor 200'),
  ('RELENT SMO','Bombona 20'),
  ('RELENT SMO','Bombona 50'),
  ('RELENT SMO','Tambor 200'),
  ('RELENT SUPER','Bombona 20'),
  ('RELENT SUPER','Bombona 50'),
  ('RELENT SUPER','Tambor 200'),
  ('RELENT W','Bombona 20'),
  ('RELENT W','Bombona 50'),
  ('RELENT W','Tambor 200'),
  ('RETARPEG S','Bombona 24'),
  ('RETARPEG S','Bombona 60'),
  ('RETARPEG S','Tambor 240'),
  ('RETARTIVE WR 2010','Bombona 24'),
  ('RETARTIVE WR 2010','Bombona 60'),
  ('RETARTIVE WR 2010','Tambor 240'),
  ('RETARTIVE WR 2010','CNT 1200'),
  ('RETARTIVE WR 2048','Bombona 22'),
  ('RETARTIVE WR 2048','Bombona 55'),
  ('RETARTIVE WR 2048','Tambor 220'),
  ('RETARTIVE WR 2048','CNT 1100'),
  ('RUST CONVERTER','Bombona 25'),
  ('RUST CONVERTER','Bombona 60'),
  ('STRUCTURAL AD CONJUNTO','Conjunto 1'),
  ('STRUCTURAL TF CONJUNTO','Conjunto 1'),
  ('SUPERFLUID AC','Bombona 24'),
  ('SUPERFLUID AC','Bombona 60'),
  ('SUPERFLUID AC','Tambor 240'),
  ('SUPERFLUID AC','CNT 1200'),
  ('WHITE MINERAL REPAIR CONJUNTO','Conjunto 40'),
  ('WP ARCON','Bombona 20'),
  ('WP ARCON','Bombona 50'),
  ('WP ARCON','Tambor 200'),
  ('WP ARPOMON','Saco 20'),
  ('WP CRYSTAL','Saco 20'),
  ('WP FLEXIBLE','Bombona 18'),
  ('WP FLEXIBLE','Bombona 42'),
  ('WP FLEXIBLE','Tambor 180'),
  ('WP HYDRACEM UF','Saco 20'),
  ('SUFLEX GREY RA','Balde 18'),
  ('SUFLEXIBLE RA','Balde 18'),
  ('SUPROFLEX CONJUNTO','Conjunto 20'),
  ('WP TILE PRO','Bombona 20'),
  ('WP TILE PRO','Bombona 50'),
  ('WP TILE PRO','Tambor 200')
) as v(produto_nome, descricao) on p.nome = v.produto_nome
on conflict (produto_id, descricao) do nothing;
